[2020-09-21 17:20:34,089] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_leer_posgres.obtener_pandas_operator 2020-09-20T00:00:00+00:00 [queued]>
[2020-09-21 17:20:34,101] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_leer_posgres.obtener_pandas_operator 2020-09-20T00:00:00+00:00 [queued]>
[2020-09-21 17:20:34,102] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-09-21 17:20:34,102] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-09-21 17:20:34,102] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-09-21 17:20:34,109] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): obtener_pandas_operator> on 2020-09-20T00:00:00+00:00
[2020-09-21 17:20:34,111] {standard_task_runner.py:53} INFO - Started process 108657 to run task
[2020-09-21 17:20:34,155] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_leer_posgres.obtener_pandas_operator 2020-09-20T00:00:00+00:00 [running]> b349191ed544
[2020-09-21 17:20:34,178] {logging_mixin.py:112} INFO - [2020-09-21 17:20:34,177] {base_hook.py:87} INFO - Using connection to: id: pg_local. Host: localhost, Port: 5432, Schema: test, Login: postgres, Password: XXXXXXXX, extra: None
[2020-09-21 17:20:34,178] {taskinstance.py:1145} ERROR - could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_lectura_posgrest.py", line 16, in obtener_pandas
    df = conn.get_pandas_df('select * from emp')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi_hook.py", line 99, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/postgres_hook.py", line 93, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

[2020-09-21 17:20:34,181] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dag_leer_posgres, task_id=obtener_pandas_operator, execution_date=20200920T000000, start_date=20200921T172034, end_date=20200921T172034
[2020-09-21 17:20:44,096] {logging_mixin.py:112} INFO - [2020-09-21 17:20:44,096] {local_task_job.py:103} INFO - Task exited with return code 1
